### ISSUE TITLE
点聚合：如何设置基础点一个点的数量，聚合之后显示数量的和

### ISSUE THREAD

**Issue by yuanhao0230** [huiyan-fe/mapvgl#103]
点配置count无效，仍然是只按照一个点计算，那我同一个位置上的多个点，只能重复循环多次吗

**Comment by wanghyper** [comment]
点聚合算法默认只进行点数量的统计，如果需要自定义，可以使用beforeRender来加载自己的渲染逻辑
http://mapv.baidu.com/gl/examples/editor.html#point-cluster-custom.html
