### ISSUE TITLE
MapV自定义主题

### ISSUE THREAD

**Issue by Embrace-code** [huiyan-fe/mapvgl#11]
![image](https://user-images.githubusercontent.com/55820435/100339217-8c85f300-3014-11eb-8b4f-7fcd8f6372e7.png)
![image](https://user-images.githubusercontent.com/55820435/100339296-a8899480-3014-11eb-9488-ca2227e05210.png)
这样 在script里面引入 但是 在设置map.setMapStyleV2({styleJson: BmapStyle})  一直报跨域错误

**Comment by Embrace-code** [comment]
各种换api.map.baidu.com/api的版本 都不对

**Comment by Junior2Ran** [comment]
关于个性化地图的使用，参考 http://lbsyun.baidu.com/index.php?title=jspopularGL/guide/custom

**Comment by Embrace-code** [comment]
![image](https://user-images.githubusercontent.com/55820435/100401510-a6ffb100-3094-11eb-86dd-550fdd78bd74.png)
![image](https://user-images.githubusercontent.com/55820435/100401527-b3840980-3094-11eb-84e5-224ebef1a9a3.png)
![image](https://user-images.githubusercontent.com/55820435/100401557-cc8cba80-3094-11eb-81fd-353d36461b11.png)
用initMap  还是 自己new的BMapGL   怎么设置 都是保这个问题 就是 根据百度个性化地图来的

**Comment by Embrace-code** [comment]
https://mapv.baidu.com/gl/examples/editor.html#threelayer-flyline.html  我从这个 完全复制下来的  官网的出来地图 在我 本地 就不出来 
![image](https://user-images.githubusercontent.com/55820435/100404280-04e3c700-309c-11eb-976b-d97156683484.png)屏幕是黑的  没有地图 就一直说这个
![image](https://user-images.githubusercontent.com/55820435/100404343-1dec7800-309c-11eb-928f-3f5b6c7befdc.png)

**Comment by Embrace-code** [comment]
问题已解决  一直知道这个时跨域问题 但是刚刚搜了下英文 是因为 我之前写的一个脚本文件把这个请求拦截了
