### ISSUE TITLE
是否支持鼠标移出移出事件？

### ISSUE THREAD

**Issue by Embrace-code** [huiyan-fe/mapvgl#16]

**Comment by Junior2Ran** [comment]
支持`onMousemove`事件

**Comment by Embrace-code** [comment]
onMouseout  和 onMouseover  移入移出  目前 还不支持吗

**Comment by Junior2Ran** [comment]
不支持，mapvgl的事件对象是整个图层，而不是单个覆盖物
如果需要判断移入移出覆盖物，需要自己在业务逻辑里实现
