### ISSUE TITLE
当地图容器的height为某些值时，textLayer图层会被PointLayer覆盖的bug

### ISSUE THREAD

**Issue by troublezzb** [huiyan-fe/mapvgl#17]
以官方demo为例：https://mapv.baidu.com/gl/examples/editor.html#od-flyline.html
修改#map_container的height为500px、501px、510px等值时，数字就会消失（textLayer图层在底层）。
或者直接调整浏览器的高度也可复现该bug。

**Comment by Junior2Ran** [comment]
收到问题，感谢
textlayer增加了depthTest属性，demo里未同步更新，下次上线会修复
