### ISSUE TITLE
空白地图支持鼠标旋转倾斜操作吗？

### ISSUE THREAD

**Issue by AimLuo** [huiyan-fe/mapvgl#2]
### 示例
[空白地图画楼块](https://mapv.baidu.com/gl/examples/editor.html#blank-shape-texture.html)
### 问题
空白地图时，如何响应鼠标的缩放之类的操作？  
尝试过以下配置无效：
```
enableDragging: true,
enableDoubleClickZoom: true,
enableScrollWheelZoom: true,
```
### 其他问题

1. cesium地图能提供个例子吗！(还没去看过cesium的使用，看了估计也不是什么问题)
2. View类的options.map的配置项有哪些，好像跟BMapGL.Map的配置项对不上啊。
3. 这个库会开源吗。

**Comment by Junior2Ran** [comment]
1.鼠标缩放操作是JSAPI里的功能，空白地图是没有的，如果要实现需要自己手动监听scroll事件改变zoom
2.在cesium里用需要修改cesium引擎
3.最基础的需要的属性和blankmap一致
4.暂时还不确定
