### ISSUE TITLE
有人把hangzhou.json找到的吗

### ISSUE THREAD

**Issue by Scholar-g** [huiyan-fe/mapvgl#23]
https://mapv.baidu.com/gl/examples/editor.html#shape-windowAnimation.html
mapvgl立体面图层shape中有个chongqing.json，怎么拿到hangzhou.json，没有数据直接凉凉

**Comment by Junior2Ran** [comment]
楼块数据为内部数据，不提供

**Comment by Scholar-g** [comment]
那这个怎么用

**Comment by Junior2Ran** [comment]
任何面数据都可以用ShapeLayer来绘制，楼块只是一个场景而已，需要你们有自己的面数据

**Comment by Scholar-g** [comment]
目前业务需求是需要杭州的，去哪里可以拿到杭州的楼块数据
