### ISSUE TITLE
多个覆盖物的重叠问题

### ISSUE THREAD

**Issue by troublezzb** [huiyan-fe/mapvgl#27]
当多个覆盖物（如IconLayer）的经纬度一致时，如何解决重叠问题？鼠标选中的是哪一个？

**Comment by Junior2Ran** [comment]
1. 如果要指定经纬度近似的几个点有固定的高地覆盖关系，可以在传入数据里的coordinates数组加一位作为高度，[x, y, z]，z值高的会在上面
2. 可以数据里带offset字段，将经纬度一致的点偏移开来

**Comment by troublezzb** [comment]
感谢答疑。z值的方案我现在才知道。
但我更希望是：iconLayer.setData(data)能自动处理（比如让几个重叠的覆盖物，稍微偏移）。

**Comment by wnf168** [comment]
20年到现在也没修复这个问题吗？唉  确实也是醉了

**Comment by chenzilong0828** [comment]
我在使用threeLayer时，导入的模型，会覆盖掉其它的图层。请问有什么解决办法呢？不论我使用的是css3Dsprite标签还是用的是MarkerListLayer，均会被我的模型所覆盖。
