### ISSUE TITLE
点聚合ClusterLayer，希望可以加上聚合点的自定义图标

### ISSUE THREAD

**Issue by advertIco** [huiyan-fe/mapvgl#28]
点聚合ClusterLayer，希望可以加上聚合点的自定义图标，现在只能设置颜色值。

**Comment by wanghyper** [comment]
最新版本已经添加该功能，具体API使用请再示例页查看

**Comment by manwuyu** [comment]
你好，

> 最新版本已经添加该功能，具体API使用请再示例页查看

https://mapv.baidu.com/gl/examples/editor.html#point-cluster.html
https://code.bdstatic.com/npm/mapvgl@1.0.0-beta.139/dist/mapvgl.min.js

没有看到如何使用

 iconOptions: {
            width: 100 / 4,
            height: 153 / 4,
            icon: 'images/marker.png',
}
这个使用无效

**Comment by daiwanxing** [comment]
> 最新版本已经添加该功能，具体API使用请再示例页查看

您好，我在文档里只看到了非聚合的自定义图标实现方式，聚合点的自定义图标实现方式暂未看到，是我遗漏了什么吗？

[clusterLayer ](https://mapv.baidu.com/gl/docs/ClusterLayer.html)
