### ISSUE TITLE
设置地图旋转角度/倾斜角度

### ISSUE THREAD

**Issue by cz495969281** [huiyan-fe/mapvgl#29]
new BMapGL.Map('map').setHeading(45); new BMapGL.Map('map').setTilt(125); 设置上无效果

**Comment by Junior2Ran** [comment]
不要这么用，setHeading和setTilt并不会返回map实例
```
var map = new BMapGL.Map('map');
map.centerAndZoom(new BMapGL.Point(116.280190, 40.049191), 19); 
map.setHeading(45);
map.setTilt(125); 
```

**Comment by cz495969281** [comment]
您好，我也是您这样写的，附件中的代码，您可以看一下，效果依然没有




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huiyan-fe/mapvgl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月31日(星期四) 中午1:19
收件人:&nbsp;"huiyan-fe/mapvgl"<mapvgl@noreply.github.com&gt;;
抄送:&nbsp;"陈泽"<495969281@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huiyan-fe/mapvgl] 设置地图旋转角度/倾斜角度 (#29)





 
不要这么用，setHeading和setTilt并不会返回map实例
 var map = new BMapGL.Map('map'); map.setHeading(45); map.setTilt(125);
