### ISSUE TITLE
尝试写的一个demo只有Line

### ISSUE THREAD

**Issue by zhengquan45** [huiyan-fe/mapvgl#3]
![image](https://user-images.githubusercontent.com/17370829/99231292-5e8dfb00-282b-11eb-9cd8-15c19ad1d8b5.png)
 除了线段的layer可用其他都会报这个错误
控制台不断出现此类警告，图层也无法显示是因为什么原因
https://github.com/zhengquan45/shaowu 这是我的案例demo

**Comment by Junior2Ran** [comment]
能提供可访问的demo页面和对应的源码么
