### ISSUE TITLE
MapVGL的文档中很多示例 都显示不出地图

### ISSUE THREAD

**Issue by cz495969281** [huiyan-fe/mapvgl#30]
可以参考一下这个示例  https://mapv.baidu.com/gl/examples/editor.html#simple-point.html

**Comment by Junior2Ran** [comment]
![image](https://user-images.githubusercontent.com/19679189/103395582-dc069400-4b69-11eb-9198-022b54eba44e.png)
看起来没什么问题

**Comment by cz495969281** [comment]
用浏览器打开是这样的，附件中有截图，您看一下，显示不出来的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huiyan-fe/mapvgl"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月31日(星期四) 中午1:13
收件人:&nbsp;"huiyan-fe/mapvgl"<mapvgl@noreply.github.com&gt;;
抄送:&nbsp;"陈泽"<495969281@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huiyan-fe/mapvgl] MapVGL的文档中很多示例 都显示不出地图 (#30)





 
Closed #30.
