### ISSUE TITLE
MapVGL 文档中 初始化百度地图引入https://mapv.baidu.com/gl/examples/static/common.js的问题

### ISSUE THREAD

**Issue by cz495969281** [huiyan-fe/mapvgl#32]
https://mapv.baidu.com/gl/examples/static/common.js 这个文件中有一个initMap方法初始化地图，发现引入后，不会渲染出地图来
下面是我的代码

 `<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
	<style type="text/css">
		html,body {
			width: 100%;
			height: 100%;
			margin: 0;
			padding: 0;
    }
    #map_container{
			width: 100%;
			height: 100%;
			margin: 0;
    }
	</style>
    <script type="text/javascript" src="https://api.map.baidu.com/api?v=1.0&type=webgl&ak=cq99z7MdWLmfaBGwVx78te42GdTIyrMQ"></script>
	<script src="https://mapv.baidu.com/gl/examples/static/common.js"></script>
	<script src="https://mapv.baidu.com/build/mapv.js"></script>
	<script src="https://code.bdstatic.com/npm/mapvgl@1.0.0-beta.54/dist/mapvgl.min.js"></script>
	<title>地图展示</title>
</head>
<body>
	<div id="map_container"></div>
    <script type="text/javascript">
        initBMap()
        // 初始化百度地图
        function initBMap(){
            var cityCenter = mapv.utilCityCenter.getCenterByCityName('上海');
            var map = initMap({
                tilt: 0,
                heading: 0,
                center: [cityCenter.lng,cityCenter.lat],
                zoom: 8,
                style: snowStyle
            });
        }
        
   
	</script>	
</body>
</html>`

**Comment by Junior2Ran** [comment]
这个common.js只是为了简化地图初始化封装的一个函数，目的是为了突出mapvgl的代码部分，和这个js无关。
地图不渲染，是因为你的代码里没有声明地图容器，建议阅读一下地图初始化的正确方式
