### ISSUE TITLE
ShapeLayer的topColor能否使用？

### ISSUE THREAD

**Issue by HiXiSi** [huiyan-fe/mapvgl#33]
看示例中是有topColor这个属性的，文档里没有直接写出来。貌似无法生效。顶部还是取的color或texture
`const layer = new mapvgl.ShapeLayer({
  blend: 'lighter',
  style: 'normal',
  color: 'rgba(0, 255, 0, 1)',
  topColor: 'rgba(255, 0, 0, 1)',
  opacity: 1
})`

**Comment by Junior2Ran** [comment]
能使用
目前有些API可能存在变更风险，或者还不够完善，所以没在文档中写出来，暂时这个属性没大问题，可以直接用
