### ISSUE TITLE
threeLayer图层render方法BUG导致Raycaster存在误差

### ISSUE THREAD

**Issue by yangyanggu** [huiyan-fe/mapvgl#35]
使用threeLayer图层加载模型时，render方法中将camera的projectionMatrix进行了强制赋值，但没有相对应的将projectionMatrixInverse也进行赋值，导致使用Raycaster判断模型点击时会存在误差。

希望在 this.camera.projectionMatrix = (new wa.Matrix4).fromArray(a.projectionMatrix);这段代码下增加
this.camera.projectionMatrixInverse = this.camera.projectionMatrix.invert();

**Comment by Junior2Ran** [comment]
感谢你的建议，我看一下

**Comment by Junior2Ran** [comment]
确实有该问题，已修复，后续上线，再次感谢~
