### ISSUE TITLE
使用electron打包桌面应用后,报错net::ERR_FAILED获取不到api

### ISSUE THREAD

**Issue by MrFanPing** [huiyan-fe/mapvgl#36]
<script src="//api.map.baidu.com/api?v=1.0&type=webgl&ak=你的密钥"></script>
2021-01-26之前是正常使用的,是因为地址变成//了吗

**Comment by Junior2Ran** [comment]
是的，这个修改导致了一些端或者桌面版产品的问题。该问题已知在修复了，如果还有问题麻烦继续留言

**Comment by AdorableLi** [comment]
> 是的，这个修改导致了一些端或者桌面版产品的问题。该问题已知在修复了，如果还有问题麻烦继续留言

我使用vue-cli创建项目，并且使用electron-builder打包项目，但是axios调用接口还是显示net::ERR_FAILED
猛男落泪
