### ISSUE TITLE
是否有更新官方文档或开源项目的计划

### ISSUE THREAD

**Issue by yangyanggu** [huiyan-fe/mapvgl#38]
RT，目前针对mapvgl进行vue版本的封装时，发现官方文档参数和方法说明跟压缩版代码里比少很多，同时也没有源码，解读压缩代码需要花费更大的精力，我想问下是不是有计划的能更新下文档，或是否有可能开放源码
我的项目地址： [https://gitee.com/guyangyang/vue-mapvgl](https://gitee.com/guyangyang/vue-mapvgl)

**Comment by Junior2Ran** [comment]
首先感谢对mapvgl的支持~
开放源码短时间内估计很难实现，官方文档的更新在计划中，会将最近更新的内容同步上去。

其次，针对”官方文档参数比代码提供的少“这个问题，需要解释的是，因为有些功能为了支持内部方便使用，还没有经过仔细的API设计与思考，功能也不够齐全、健壮，直接暴露出来可能反而给用户造成困扰；其中包括一些实验中的图层，也面临重构或者API完全推翻的可能，所以也没有放到文档里。

**Comment by Junior2Ran** [comment]
如果方便可以私我邮箱一个你的联系方式，有问题或者对mapvgl有好的意见都欢迎交流

**Comment by yangyanggu** [comment]
已将联系方式发送你的邮箱，谢谢

**Comment by Junior2Ran** [comment]
没收到，直接加我微信hdr001
