### ISSUE TITLE
只有重庆的json文件吗？

### ISSUE THREAD

**Issue by webgaochao** [huiyan-fe/mapvgl#4]
不知道怎么获取其他区域的json文件

**Comment by AimLuo** [comment]
自己去[geojson.io](http://geojson.io/)画，当然也可以用`gis`绘图软件来画。

**Comment by webgaochao** [comment]
geojson数据好像并不行，生成的坐标点加楼层数。重庆的json文件格式没看懂

**Comment by webgaochao** [comment]
geojson数据好像并不行，生成的坐标点加比例数。重庆的json文件格式没看懂

**Comment by AimLuo** [comment]
> geojson数据好像并不行，生成的坐标点加比例数。重庆的json文件格式没看懂

重庆的数据用的`BBox`数据集为了减少传输量，代码中用以下代码转换成标准的`geojson`  
```
......
     var data = rs;
        var polygons = [];
        var len = data.length;
        for (var i = 0; i < len; i++) {
......
```

**Comment by ab690257072** [comment]
> > geojson数据好像并不行，生成的坐标点加比例数。重庆的json文件格式没看懂
> 
> 重庆的数据用的`BBox`数据集为了减少传输量，代码中用以下代码转换成标准的`geojson`
> 
> ```
> ......
>      var data = rs;
>         var polygons = [];
>         var len = data.length;
>         for (var i = 0; i < len; i++) {
> ......
> ```

请问下，官网demo里的bbox格式好像不是坐标，若我有geojson，则如何转换为官网的bbox格式？

**Comment by amangqq** [comment]
> > > geojson数据好像并不行，生成的坐标点加比例数。重庆的json文件格式没看懂
> > 
> > 
> > 重庆的数据用的`BBox`数据集为了减少传输量，代码中用以下代码转换成标准的`geojson`
> > ```
> > ......
> >      var data = rs;
> >         var polygons = [];
> >         var len = data.length;
> >         for (var i = 0; i < len; i++) {
> > ......
> > ```
> 
> 请问下，官网demo里的bbox格式好像不是坐标，若我有geojson，则如何转换为官网的bbox格式？

转成功了吗

**Comment by lovezjj008** [comment]
垃圾
