### ISSUE TITLE
使用mapvgl的几点疑问

### ISSUE THREAD

**Issue by landonzeng** [huiyan-fe/mapvgl#40]
目前项目里有个需求，需要在地图上展示小区边界、小区中心坐标，以及行政区边界等信息，数据量还蛮大的，差不多有1000万的样子吧，mapvgl确实蛮好用的，但是现在用下来有几个疑问
1、PolygonLayer和ShapeLayer两个哪个更适合地图上多边形（小区边界）展示，哪个性能更优？
2、PolygonLayer、ShapeLayer是否可以添加zIndex这类属性，因为目前项目里需要将行政区这类多边形做为底层，然后小区多边形这类的叠加在上层，目前的话容易导致图层叠加，而且发现多边形的边界线不是根据形成的多边形呈现，而是根据点坐标来的，有些多边形可能并没有收尾相连，然后导致呈现出来的多边形缺少一边，但是由于设置了背景色，所以呈现出的边界先显得尤为怪异，是否可以根据形成的多边形来渲染边界线呢？
3、发现多边形的方法里没有类似于text这种展示文字的属性，需要在添加TextLayer图层叠加上去，有些不方便
以上纯属个人使用中遇到的问题，有什么不足之处，望谅解 :D

**Comment by Junior2Ran** [comment]
1. PolygonLayer实现上是由Shape和Line组合而成的，所以性能上Shape肯定优于Polygon，看你的需求是否对边界线有要求
2. 边界线确实没有做闭合处理，后面我会加上这块逻辑
3. 后面有计划做一个GeoJsonLayer，由Shape、Line、Text组合而成，其实和你的处理逻辑一样
4. 面重合时有2个方案可以解决，一是更改数据里的z坐标，让小区的z值高于行政区的z值，二是当两者z值一样或特别相近时，可以使用内置的一个名为polygonOffset属性，这是一个长度为2的数组，可以传入`[1, 1]`或者`[-10, -10]`这样的值拉开两者的深度，现在该属性是实验中属性，且只有Shape和Line支持，所以没有公开到文档里

**Comment by landonzeng** [comment]
> 1. PolygonLayer实现上是由Shape和Line组合而成的，所以性能上Shape肯定优于Polygon，看你的需求是否对边界线有要求
> 2. 边界线确实没有做闭合处理，后面我会加上这块逻辑
> 3. 后面有计划做一个GeoJsonLayer，由Shape、Line、Text组合而成，其实和你的处理逻辑一样
> 4. 面重合时有2个方案可以解决，一是更改数据里的z坐标，让小区的z值高于行政区的z值，二是当两者z值一样或特别相近时，可以使用内置的一个名为polygonOffset属性，这是一个长度为2的数组，可以传入`[1, 1]`或者`[-10, -10]`这样的值拉开两者的深度，现在该属性是实验中属性，且只有Shape和Line支持，所以没有公开到文档里

好的，非常感谢您从百忙之中回答我的疑问，谢谢
问题1中，小区的多边形展示倾向于块的展示，然后我们会将对应楼栋的坐标点也呈现在地图上，这样就可以清晰的呈现出某个小区里有多少栋楼的量，所以倾向于块与点的展示
回答4中的z坐标是指zIndex这个属性吗？我用了，没有效果，然后发现PolygonLayer里的onDblClick和onRightClick方法均无效

当前项目主要是使用平面地图，未使用3d地图
基本上效果如下图
![map](https://user-images.githubusercontent.com/7336781/108488597-89309980-72db-11eb-8dae-7c1fc444ef14.png)

**Comment by Junior2Ran** [comment]
z不是zIndex属性，是data里的坐标，coordinates字段，可以传入[x, y, z]格式

**Comment by landonzeng** [comment]
> z不是zIndex属性，是data里的坐标，coordinates字段，可以传入[x, y, z]格式

哦哦，明白了，我先去试试看，谢谢了，期待新的版本发布
