### ISSUE TITLE
怎么给点聚合图层中的每个点加个 文字图层，要保证文字图层随着带聚合中的点出现和消失，类似于2.0中点聚合中的 marker.setLabel().

### ISSUE THREAD

**Issue by xwyweitian** [huiyan-fe/mapvgl#48]
怎么给点聚合图层中的每个点加个 文字图层，要保证文字图层随着带聚合中的点出现和消失，类似于2.0中点聚合中的
marker.setLabel().

**Comment by wanghyper** [comment]
试下这个https://mapv.baidu.com/gl/examples/editor.html#point-cluster-custom.html
