### ISSUE TITLE
mapvgl挂了？Uncaught TypeError: Cannot read property 'getExtension' of null

### ISSUE THREAD

**Issue by haihaishuaige** [huiyan-fe/mapvgl#49]
mapvgl挂了？之前项目用的一些飞线动画全都报错，官网的实例demo也全部挂了，报的是同一个错

**Comment by hxun9823** [comment]
你好 我也遇到同样的问题了 怎么解决的

**Comment by Harpoonhu** [comment]
> mapvgl挂了？之前项目用的一些飞线动画全都报错，官网的实例demo也全部挂了，报的是同一个错

你好 我也遇到同样的问题了 怎么解决的
