### ISSUE TITLE
反复点击加载地图会出现WARNING: Too many active WebGL contexts. Oldest context will be lost.

### ISSUE THREAD

**Issue by 472527381** [huiyan-fe/mapvgl#50]
这个是内存泄漏造成的吗？需要像其他图形工具一样离开页面时候清除map吗？如果是的话需要怎么去清除。。在官方文档没找到介绍

**Comment by Junior2Ran** [comment]
1.升级到新版的mapvgl
2.地图需要销毁前执行view.destroy()和map.destroy()

**Comment by 472527381** [comment]
> 1.升级到新版的mapvgl
> 2.地图需要销毁前执行view.destroy（）和map.destroy（）

好的。谢谢。我去试一下

**Comment by Guard-233** [comment]
可以在同一个页面使用css属性去隐藏一个dom，不要删除dom再创建。但是离开页面的时候，需要使用destroy之类的方法把实例销毁

**Comment by Junior2Ran** [comment]
> 可以在同一个页面使用css属性去隐藏一个dom，不要删除dom再创建。但是离开页面的时候，需要使用destroy之类的方法把实例销毁

这个也是可以采用的合理办法
