### ISSUE TITLE
chrome中无法显示

### ISSUE THREAD

**Issue by kuangche** [huiyan-fe/mapvgl#54]
[
![image](https://user-images.githubusercontent.com/5680345/118977444-bbb86400-b9a8-11eb-89b8-76f772411abe.png)
](url)

**Comment by kuangche** [comment]
看样纸是少了个canvas啊

**Comment by Junior2Ran** [comment]
https://mapv.baidu.com/gl/examples/point-simple.html

**Comment by Junior2Ran** [comment]
截图的url看起来底图和审查元素都不一样呀
![image](https://user-images.githubusercontent.com/19679189/119304120-5fe82680-bc99-11eb-9a6a-7f57cbd1cd89.png)
