### ISSUE TITLE
ClusterLayer的beforRender钩子出现死循环并导致页面卡死

### ISSUE THREAD

**Issue by tomee-oy** [huiyan-fe/mapvgl#56]
当地图拖拽或者缩放到beforRender拿到空数据的时候，beforeRender会被循环调用，导致浏览器爆栈。
[官方demo](https://mapv.baidu.com/gl/examples/editor.html#point-cluster-custom.html)即可复现问题。

**Comment by Junior2Ran** [comment]
已修复，请更新到 1.0.0-beta.127 版本以上使用

**Comment by tomee-oy** [comment]
> 已修复，请更新到 1.0.0-beta.127 版本以上使用

请问，目前最新版本号是多少？

**Comment by tomee-oy** [comment]
> 已修复，请更新到 1.0.0-beta.127 版本以上使用

更新到127版本，当zoom超过maxZoom并且data为空的时候，依然存在这个问题。我用的是html的header中内嵌js的方式引入，并非esm的方式，有区别没？

**Comment by wanghyper** [comment]
官网示例已更新，请确认问题是否仍存在

**Comment by tomee-oy** [comment]
> 官网示例已更新，请确认问题是否仍存在

官网示例已经没有问题了，项目中更新了react-bmapgl包也没有问题了。
