### ISSUE TITLE
通过websocket获取数据 setData() 会导致页面卡死

### ISSUE THREAD

**Issue by zwtvip** [huiyan-fe/mapvgl#57]

**Comment by zwtvip** [comment]
我用了官网列子，使用定时器生成数据，然后 layer.setData(data), 页面直接无响应

**Comment by Junior2Ran** [comment]
请给出可复现的页面，以便分析原因

**Comment by zwtvip** [comment]
var data = [];
  var citys = [
      '北京', '天津', '上海', '重庆', '石家庄', '太原', '呼和浩特', '哈尔滨',
      '长春', '沈阳', '济南', '南京', '合肥', '杭州', '南昌', '福州', '郑州',
      '武汉', '长沙', '广州', '南宁', '西安', '银川', '兰州', '西宁', '乌鲁木齐',
      '成都', '贵阳', '昆明', '拉萨', '海口'
  ];
  var markers = [
      'images/marker.png',
      'images/icons/icon-accident.png',
      'images/icons/icon-airplane.png',
      'images/icons/icon-location.png',
      'images/icons/label-accident.png',
      'images/icons/label-jam.png',
      'images/icons/label-warning.png',
  ];

  var randomCount = 100;
  var layer;

  setInterval(function(){
      // 构造数据
      while (randomCount--) {
          var cityCenter = mapv.utilCityCenter.getCenterByCityName(citys[parseInt(Math.random() * citys.length, 10)]);
          data.push({
              geometry: {
                  type: 'Point',
                  coordinates: [cityCenter.lng - 2 + Math.random() * 4, cityCenter.lat - 2 + Math.random() * 4]
              },
              // properties: {
              //     icon: markers[Math.floor(Math.random() * markers.length)]
              // }
          });
      }
      layer.setData(data);
   },5000)

  var view = new mapvgl.View({
      map: map
  });

   layer = new mapvgl.IconLayer({
      width: 100 / 4,
      height: 153 / 4,
      offset: [0, -153 / 8],
      opacity: 0.8,
      icon: 'images/marker.png',
      enablePicked: true, // 是否可以拾取
      selectedIndex: -1, // 选中项
      selectedColor: '#ff0000', // 选中项颜色
      autoSelect: true, // 根据鼠标位置来自动设置选中项
      onClick: (e) => { // 点击事件
          console.log('click', e);
      },
      onDblClick: e => {
          console.log('double click', e);
      },
      onRightClick: e => {
          console.log('right click', e);
      }
  });
  view.addLayer(layer);
  layer.setData(data);

  map.setDefaultCursor('default');

**Comment by zwtvip** [comment]
> 请给出可复现的页面，以便分析原因

var data = [];
var citys = [
'北京', '天津', '上海', '重庆', '石家庄', '太原', '呼和浩特', '哈尔滨',
'长春', '沈阳', '济南', '南京', '合肥', '杭州', '南昌', '福州', '郑州',
'武汉', '长沙', '广州', '南宁', '西安', '银川', '兰州', '西宁', '乌鲁木齐',
'成都', '贵阳', '昆明', '拉萨', '海口'
];
var markers = [
'images/marker.png',
'images/icons/icon-accident.png',
'images/icons/icon-airplane.png',
'images/icons/icon-location.png',
'images/icons/label-accident.png',
'images/icons/label-jam.png',
'images/icons/label-warning.png',
];

var randomCount = 100;
var layer;

setInterval(function(){
// 构造数据
while (randomCount--) {
var cityCenter = mapv.utilCityCenter.getCenterByCityName(citys[parseInt(Math.random() * citys.length, 10)]);
data.push({
geometry: {
type: 'Point',
coordinates: [cityCenter.lng - 2 + Math.random() * 4, cityCenter.lat - 2 + Math.random() * 4]
},
// properties: {
// icon: markers[Math.floor(Math.random() * markers.length)]
// }
});
}
layer.setData(data);
},5000)

var view = new mapvgl.View({
map: map
});

layer = new mapvgl.IconLayer({
width: 100 / 4,
height: 153 / 4,
offset: [0, -153 / 8],
opacity: 0.8,
icon: 'images/marker.png',
enablePicked: true, // 是否可以拾取
selectedIndex: -1, // 选中项
selectedColor: '#ff0000', // 选中项颜色
autoSelect: true, // 根据鼠标位置来自动设置选中项
onClick: (e) => { // 点击事件
console.log('click', e);
},
onDblClick: e => {
console.log('double click', e);
},
onRightClick: e => {
console.log('right click', e);
}
});
view.addLayer(layer);
layer.setData(data);

map.setDefaultCursor('default');

**Comment by zwtvip** [comment]
> > 请给出可复现的页面，以便分析原因
> 
> var data = [];
> var citys = [
  > '北京', '天津', '上海', '重庆', '石家庄', '太原', '呼和浩特', '哈尔滨',
  > '长春', '沈阳', '济南', '南京', '合肥', '杭州', '南昌', '福州', '郑州',
  > '武汉', '长沙', '广州', '南宁', '西安', '银川', '兰州', '西宁', '乌鲁木齐',
  > '成都', '贵阳', '昆明', '拉萨', '海口'
> ];
> var markers = [
  > 'images/marker.png',
  > 'images/icons/icon-accident.png',
  > 'images/icons/icon-airplane.png',
  > 'images/icons/icon-location.png',
  > 'images/icons/label-accident.png',
  > 'images/icons/label-jam.png',
  > 'images/icons/label-warning.png',
> ];
> 
> var randomCount = 100;
> var layer;
> 
> setInterval(function(){
  > // 构造数据
  > while (randomCount--) {
  > var cityCenter = mapv.utilCityCenter.getCenterByCityName(citys[parseInt(Math.random() * citys.length, 10)]);
  > data.push({
    > geometry: {
      > type: 'Point',
      > coordinates: [cityCenter.lng - 2 + Math.random() * 4, cityCenter.lat - 2 + Math.random() * 4]
    > },
  > // properties: {
  > // icon: markers[Math.floor(Math.random() * markers.length)]
  > // }
  > });
> }
   >layer.setData(data);
> },5000)
> 
> var view = new mapvgl.View({
   > map: map
> });
> 
> layer = new mapvgl.IconLayer({
    > width: 100 / 4,
    > height: 153 / 4,
    > offset: [0, -153 / 8],
    > opacity: 0.8,
    > icon: 'images/marker.png',
    > enablePicked: true, // 是否可以拾取
    > selectedIndex: -1, // 选中项
    > selectedColor: '#ff0000', // 选中项颜色
    > autoSelect: true, // 根据鼠标位置来自动设置选中项
    > onClick: (e) => { // 点击事件
       > console.log('click', e);
    > },
    > onDblClick: e => {
       > console.log('double click', e);
    > },
    > onRightClick: e => {
       > console.log('right click', e);
    > }
> });
> view.addLayer(layer);
> layer.setData(data);
> 
> map.setDefaultCursor('default');
