### ISSUE TITLE
研究了下，好像没法在3D建筑上显示自定义icon。就是类似于BMapGL.Marker3D，根据geojson画完建筑3D后建筑会挡住其他

### ISSUE THREAD

**Issue by webgaochao** [huiyan-fe/mapvgl#6]

**Comment by AimLuo** [comment]
个人觉得，百度地图仅仅是为了响应用户的旋转，倾斜，放大缩小这些视角转场的功能，反而地理位置是次要的。
至于你这种在建筑物上画图标，官方倒是提供了画窗户的功能。  
其实要实现比较复杂效果，只能用threeJs写自定义图层。

**Comment by Junior2Ran** [comment]
mapvgl和jsapi并不共用一个canvas，只是两者有同样的矩阵变化，所以会导致mapvgl的所有图层都会覆盖bmapgl的覆盖物。mapvgl自身的图层会根据坐标和绘制的先后顺序决定覆盖关系
