### ISSUE TITLE
设置renderOrder无效

### ISSUE THREAD

**Issue by fullonce** [huiyan-fe/mapvgl#66]
![image](https://user-images.githubusercontent.com/39945052/127983704-10ba194d-bca7-4dad-ba1c-89dc48af16ed.png)
设置renderOrder 无效 ，值为20的 图层还是被值为10的覆盖了

**Comment by Junior2Ran** [comment]
需要更新成`1.0.0-beta.131`版本以上才能生效

**Comment by fullonce** [comment]
使用 https://code.bdstatic.com/npm/mapvgl@1.0.0-beta.131/dist/mapvgl.min.js 还是无效

**Comment by fullonce** [comment]
> 需要更新成`1.0.0-beta.131`版本以上才能生效

使用https://code.bdstatic.com/npm/mapvgl@1.0.0-beta.131/dist/mapvgl.min.js 还是无效

**Comment by EmperorFront** [comment]
renderer还需要设置下：
    const renderer = new THREE.WebGLRenderer();
    renderer.sortObjects = true;
