### ISSUE TITLE
是否支持自动应用 properties 中的样式

### ISSUE THREAD

**Issue by vvizden** [huiyan-fe/mapvgl#94]
请问是否支持自动应用 properties 中的样式，比如 LineLayer，否则还得自己拆分出所有的 feature，每一个 feature 单独对应一个 layer ，然后单独设置 color 和 width 吗?

**Comment by Junior2Ran** [comment]
支持，properties内属性名对应color和width

**Comment by hpy0826** [comment]
感谢这个问题，亲测polygon也有效
