### ISSUE TITLE
请问iconlayer如何自定义icon

### ISSUE THREAD

**Issue by makaikai6688** [huiyan-fe/mapvgl#95]
var layer = new mapvgl.IconLayer({
    width: 100 / 2,
    height: 153 / 2,
    icon: 'https://mapopen-website-wiki.bj.bcebos.com/demos/JS.png',
});
通过url设置icon，没有加载出新图片，反而加载出来了红色的倒三角行，请问是这种设置icon的方式不对，还是什么原因，谢谢

**Comment by spike-byte** [comment]
你好 这个问题怎么解决的

**Comment by itagan** [comment]
定义没错

**Comment by LiuJianhuo** [comment]
> var layer = new mapvgl.IconLayer({ width: 100 / 2, height: 153 / 2, icon: 'https://mapopen-website-wiki.bj.bcebos.com/demos/JS.png', }); 通过url设置icon，没有加载出新图片，反而加载出来了红色的倒三角行，请问是这种设置icon的方式不对，还是什么原因，谢谢

解决了吗
